= JAR file analyzer
:linkattrs:
:project-owner:      kordamp
:project-name:       jarviz
:project-groupId:    org.kordamp.jarviz
:project-artifactId: jarviz-core
:project-version: 0.1.0

image:http://img.shields.io/github/actions/workflow/status/{project-owner}/{project-name}/early-access.yml?branch=main&logo=github&label=Build["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-groupId}/{project-artifactId}.svg[Download, link="https://search.maven.org/#search|ga|1|g:{project-groupId} AND a:{project-artifactId}"]
image:https://slsa.dev/images/gh-badge-level3.svg["SLSA 3", link="https://slsa.dev"]
image:https://img.shields.io/github/downloads/{project-owner}/{project-name}/total[GitHub all releases]

---

Jarviz is a JAR file analyzer tool.  You can obtain metadata from a JAR such as its manifest, manifest entries,
bytecode versions, declarative services, and more.

[source]
----
Jarviz is a JAR file analyzer tool
Usage: jarviz [-hV] [-D=<key=value>]... [COMMAND]

Options:
  -D=<key=value>
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.

Commands:
  bytecode             Commands for the JAR's bytecode
  manifest             Commands for the JAR's manifest
  services             Commands for declarative services
  generate-completion  Generate bash/zsh completion script for jarviz.

Documentation found at https://github.com/kordamp/jarviz
----

== Commands

=== Bytecode

.show

[source]
----
$ jarviz btecode show --gav --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0
Unversioned classes. Bytecode version: 47 total: 9
Unversioned classes. Bytecode version: 48 total: 239
Unversioned classes. Bytecode version: 49 total: 358
Unversioned classes. Bytecode version: 50 total: 896
Unversioned classes. Bytecode version: 51 total: 2089
Unversioned classes. Bytecode version: 52 total: 3366
Unversioned classes. Bytecode version: 53 total: 1
----

[source]
----
$ jarviz bytecode show --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0 \
    --bytecode-version 47 --details
Unversioned classes. Bytecode version: 47 total: 9
org.aopalliance.aop.Advice
org.aopalliance.aop.AspectException
org.aopalliance.intercept.ConstructorInterceptor
org.aopalliance.intercept.ConstructorInvocation
org.aopalliance.intercept.Interceptor
org.aopalliance.intercept.Invocation
org.aopalliance.intercept.Joinpoint
org.aopalliance.intercept.MethodInterceptor
org.aopalliance.intercept.MethodInvocation
----

`jackson-core` is an MR-JAR.

[source]
----
$ jarviz bytecode show --gav com.fasterxml.jackson.core:jackson-core:2.14.1
Unversioned classes. Bytecode version: 52 total: 160
Versioned classes 9. Bytecode version: 53 total: 1

$ jarviz bytecode show --gav com.fasterxml.jackson.core:jackson-core:2.14.1 \
    --bytecode-version 53 --details
Versioned classes 9. Bytecode version: 53 total: 1
module-info
----

=== Manifest

.show

[source]
----
$ jarviz manifest show --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0
Manifest-Version: 1.0
Created-By: Maven Jar Plugin 3.2.0
Build-Jdk-Spec: 11
Implementation-Title: pomchecker-toolprovider
Implementation-Version: 1.4.0
Implementation-Vendor: Kordamp
Automatic-Module-Name: org.kordamp.maven.pomchecker
Build-Jdk: 9 (Azul Systems, Inc. 11.0.17+8-LTS)
Build-OS: Linux amd64 5.15.0-1022-azure
Build-Revision: b252400e16942f5f944ecec68914e264f2fe37af
Build-Timestamp: 2022-10-31T18:52:24Z
Main-Class: org.kordamp.maven.checker.toolprovider.Pomchecker

----

.query

[source]
----
$ jarviz manifest query --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0 \
    --attribute-name Automatic-Module-Name
org.kordamp.maven.pomchecker
----

=== Services

.list

[source]
----
$ jarviz services list --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0
org.slf4j.spi.SLF4JServiceProvider
java.util.spi.ToolProvider
javax.annotation.processing.Processor
org.apache.commons.logging.LogFactory
----

.show

[source]
----
$ jarviz services show --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0 \
    --service-name java.util.spi.ToolProvider
org.kordamp.maven.checker.toolprovider.Pomchecker
----

== Install

=== Early Access

*JBang*

[source]
[subs="attributes"]
----
// Download, cache, and run
jbang {project-name}-snapshot@{project-owner} &lt;command&gt; [&lt;args&gt;]
----

*manually*

Download the pre-compiled binary matching your OS and processor from the link:https://github.com/{project-owner}/{project-name}/releases/tag/early-access[releases page],
uncompress and copy to the desired location.

NOTE: Be mindful that `{project-name}-early-access.zip` requires Java 11 to be installed while
`{project-name}-standalone-early-access-*.zip` can be used without a previous installation of Java as
it includes its own Java Runtime.

=== Stable

*Sdkman*

Requires Java 11
[source]
[subs="attributes"]
----
sdk install {project-name}
----

*Homebrew tap*

[source]
[subs="attributes"]
----
brew install {project-owner}/tap/{project-name}
----

*Scoop*:

Requires Java 11
[source]
[subs="attributes"]
----
scoop bucket add {project-name} https://github.com/{project-owner}/scoop-{project-name}.git
scoop install {project-name}
----

*JBang*

[source]
[subs="attributes"]
----
// Download, cache, and run
jbang {project-name}@{project-owner} &lt;command&gt; [&lt;args&gt;]
----

*manually*

Download the pre-compiled binary matching your OS and processor from the link:https://github.com/{project-owner}/{project-name}/releases/tag/v{project-version}[releases page],
uncompress and copy to the desired location.

NOTE: Be mindful that `{project-name}-{project-version}.zip` requires Java 11 to be installed while
`{project-name}-standalone-{project-version}-*.zip` can be used without a previous installation of Java as
it includes its own Java Runtime.

== Community

 * Ask questions on our link:https://github.com/{project-owner}/{project-name}/discussions[Discussions] page.
 * image:https://img.shields.io/twitter/follow/{project-owner}?style=social[Twitter Follow]
 * Join our link:CONTRIBUTORS.md[contributors] by reporting bugs, proposing features, sending patches, promoting the project, helping others.

== Code of Conduct

This project adheres to a link:https://github.com/{project-owner}/{project-name}/blob/main/CODE_OF_CONDUCT.md[code of conduct].
By participating, you are expected to uphold this code. We appreciate your contribution. Please refer to our
link:https://github.com/{project-owner}/{project-name}/blob/main/CONTRIBUTING.adoc[contributing guidelines] for further information.
