= JAR file analyzer
:linkattrs:
:project-owner:      kordamp
:project-name:       jarviz
:project-groupId:    org.kordamp.jarviz
:project-artifactId: jarviz-core
:project-version: 0.2.0

image:http://img.shields.io/github/actions/workflow/status/{project-owner}/{project-name}/early-access.yml?branch=main&logo=github&label=Build["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-groupId}/{project-artifactId}.svg[Download, link="https://search.maven.org/#search|ga|1|g:{project-groupId} AND a:{project-artifactId}"]
image:https://slsa.dev/images/gh-badge-level3.svg["SLSA 3", link="https://slsa.dev"]
image:https://img.shields.io/github/downloads/{project-owner}/{project-name}/total[GitHub all releases]

---

Jarviz is a JAR file analyzer tool.  You can obtain metadata from a JAR such as its manifest, manifest entries,
bytecode versions, declarative services, Java module descriptors and more.

[source]
----
Jarviz is a JAR file analyzer tool
Usage: jarviz [-hV] [-D=<key=value>]... [COMMAND]

Options:
  -D=<key=value>
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.

Commands:
  bytecode             Commands for the JAR's bytecode.
  manifest             Commands for the JAR's manifest.
  module               Commands for modular JARs.
  services             Commands for declarative services.
  generate-completion  Generate bash/zsh completion script for jarviz.

Documentation found at https://github.com/kordamp/jarviz
----

== Commands

=== Bytecode

*show*

Show the JAR's bytecode version(s).
Will show the value of the `Bytecode-Version` manifest attribute
if it exists; an ordered list of total unversioned classes per
bytecode version; an ordered list of total versioned classes.

[source]
----
$ jarviz bytecode show --gav org.kordamp.maven:pomchecker-toolprovider:1.8.0
subject: pomchecker-toolprovider-1.8.0.jar
Unversioned classes. Bytecode version: 47 total: 9
Unversioned classes. Bytecode version: 48 total: 239
Unversioned classes. Bytecode version: 49 total: 314
Unversioned classes. Bytecode version: 50 total: 896
Unversioned classes. Bytecode version: 51 total: 595
Unversioned classes. Bytecode version: 52 total: 4,571
Unversioned classes. Bytecode version: 53 total: 2
----

Use the `--details` flag to list all classes per bytecode version

[source]
----
$ jarviz bytecode show --gav org.kordamp.maven:pomchecker-toolprovider:1.8.0 \
    --bytecode-version 47 --details
subject: pomchecker-toolprovider-1.8.0.jar
Unversioned classes. Bytecode version: 47 total: 9
org.aopalliance.aop.Advice
org.aopalliance.aop.AspectException
org.aopalliance.intercept.ConstructorInterceptor
org.aopalliance.intercept.ConstructorInvocation
org.aopalliance.intercept.Interceptor
org.aopalliance.intercept.Invocation
org.aopalliance.intercept.Joinpoint
org.aopalliance.intercept.MethodInterceptor
org.aopalliance.intercept.MethodInvocation
----

`jackson-core` is an Multi Release JAR (MR-JAR).

[source]
----
$ jarviz bytecode show --gav com.fasterxml.jackson.core:jackson-core:2.14.1
subject: jackson-core-2.14.1.jar
Unversioned classes. Bytecode version: 52 total: 160
Versioned classes 9. Bytecode version: 53 total: 1

$ jarviz bytecode show --gav com.fasterxml.jackson.core:jackson-core:2.14.1 \
    --bytecode-version 53 --details
subject: jackson-core-2.14.1.jar
Versioned classes 9. Bytecode version: 53 total: 1
module-info
----

=== Manifest

*show*

Show the JAR's manifest.

[source]
----
$ jarviz manifest show --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0
subject: pomchecker-toolprovider-1.4.0.jar
Manifest-Version: 1.0
Created-By: Maven Jar Plugin 3.2.0
Build-Jdk-Spec: 11
Implementation-Title: pomchecker-toolprovider
Implementation-Version: 1.4.0
Implementation-Vendor: Kordamp
Automatic-Module-Name: org.kordamp.maven.pomchecker
Build-Jdk: 9 (Azul Systems, Inc. 11.0.17+8-LTS)
Build-OS: Linux amd64 5.15.0-1022-azure
Build-Revision: b252400e16942f5f944ecec68914e264f2fe37af
Build-Timestamp: 2022-10-31T18:52:24Z
Main-Class: org.kordamp.maven.checker.toolprovider.Pomchecker
----

*query*

Query manifest attributes.

[source]
----
$ jarviz manifest query --gav org.kordamp.maven:pomchecker-toolprovider:1.4.0 \
    --attribute-name Automatic-Module-Name
subject: pomchecker-toolprovider-1.4.0.jar
Automatic-Module-Name: org.kordamp.maven.pomchecker
----

=== Module

*name*

Show the module name.
Will show the module name, whether it's automatic or not, and if the name is valid.

`slf4j-api:1.7.36` defines an `Automatic-Module-Name` in its manifest

[source]
----
$ jarviz module name --gav org.slf4j:slf4j-api:1.7.36
subject: slf4j-api-1.7.36.jar
name: org.slf4j
source: manifest
automatic: true
valid: true
----

`slf4j-api:2.0.6` defines a full module descriptor

[source]
----
$ jarviz module name --gav org.slf4j:slf4j-api:2.0.6
subject: slf4j-api-2.0.6.jar
name: org.slf4j
source: explicit
automatic: false
valid: true
----

This JAR filename is invalid

[source]
----
$ jarviz module name --file foo-1-TAG.jar
subject: foo-1-TAG.jar
name: foo.1.TAG
source: filename
automatic: true
valid: false
reason: foo.1.TAG: Invalid module name: '1' is not a Java identifier
----

*descriptor*

Show the module descriptor in detail.

[source]
----
$ jarviz module descriptor --gav jakarta.activation:jakarta.activation-api:2.1.1
subject: jakarta.activation-api-2.1.1.jar
name: jakarta.activation
version: 2.1.1
open: false
automatic: false
exports:
  jakarta.activation
  jakarta.activation.spi
requires:
  java.base mandated
  java.desktop static
  java.logging
uses:
  jakarta.activation.spi.MailcapRegistryProvider
  jakarta.activation.spi.MimeTypeRegistryProvider
----

=== Packages

*split*

Display split packages

[source]
----
$ jarviz packages split --directory ~/.sdkman/candidates/maven/current/lib/
subject: maven-artifact-3.9.0.jar
org.apache.maven.artifact
org.apache.maven.artifact.handler
org.apache.maven.artifact.metadata
org.apache.maven.artifact.repository
org.apache.maven.artifact.repository.layout
org.apache.maven.artifact.repository.metadata
org.apache.maven.artifact.resolver
org.apache.maven.artifact.resolver.filter
org.apache.maven.artifact.versioning
org.apache.maven.repository
org.apache.maven.repository.legacy.metadata

subject: maven-compat-3.9.0.jar
org.apache.maven.artifact
org.apache.maven.artifact.repository
org.apache.maven.artifact.repository.layout
org.apache.maven.artifact.repository.metadata
org.apache.maven.artifact.resolver
org.apache.maven.artifact.resolver.filter
org.apache.maven.artifact.versioning
org.apache.maven.execution
org.apache.maven.project
org.apache.maven.project.path
org.apache.maven.repository

...
----

=== Services

*list*

Display registered services.

[source]
----
$ jarviz services list --gav org.kordamp.maven:pomchecker-toolprovider:1.8.0
subject: pomchecker-toolprovider-1.8.0.jar
java.util.spi.ToolProvider
javax.annotation.processing.Processor
org.apache.commons.logging.LogFactory
org.slf4j.spi.SLF4JServiceProvider
----

*show*

Display service implementations for a given service.

[source]
----
$ jarviz services show --gav org.kordamp.maven:pomchecker-toolprovider:1.8.0 \
    --service-name java.util.spi.ToolProvider
subject: pomchecker-toolprovider-1.8.0.jar
service: java.util.spi.ToolProvider
org.kordamp.maven.checker.toolprovider.Pomchecker
----

== Reports

All commands accept the following settings for generating reports:

[source]
----
--report-format=<format>
                Report format to use. Repeatable.
--report-path=<reportPath>
                Path to report filename (without extension)
----

Format may be any of [`txt`, `xml`, `json`, `yaml`].

.Example

[source]
----
$ jarviz module name --gav com.sun.mail:jakarta.mail:2.0.1 \
    --report-path jakarta.mail \
    --report-format txt \
    --report-format xml \
    --report-format json \
    --report-format yaml
subject: jakarta.mail-2.0.1.jar
name: jakarta.mail
source: explicit
automatic: false
valid: true
----

[source]
.jakarta.mail.txt
----
subjects:
  subject:
    command: module name
    jar:
      file: jakarta.mail-2.0.1.jar
      size: 689294
      sha256: 8988bdbde922ee173db7179e23393dd2258f3b64f708f41082e03f0e0494cc23
    result:
      name: jakarta.mail
      source: explicit
      automatic: false
      valid: true
----

[source,xml]
[subs="verbatim"]
.jakarta.mail.xml
----
<jarviz>
  <subjects>
    <subject>
      <command>module name</command>
      <jar>
        <file>jakarta.mail-2.0.1.jar</file>
        <size>689294</size>
        <sha256>8988bdbde922ee173db7179e23393dd2258f3b64f708f41082e03f0e0494cc23</sha256>
      </jar>
      <result>
        <name>jakarta.mail</name>
        <source>explicit</source>
        <automatic>false</automatic>
        <valid>true</valid>
      </result>
    </subject>
  </subjects>
</jarviz>
----

[source,json]
.jakarta.mail.json
----
{
  "subjects": [
    {
      "command": "module name",
      "jar": {
        "file": "jakarta.mail-2.0.1.jar",
        "size": 689294,
        "sha256": "8988bdbde922ee173db7179e23393dd2258f3b64f708f41082e03f0e0494cc23"
      },
      "result": {
        "name": "jakarta.mail",
        "source": "explicit",
        "automatic": false,
        "valid": true
      }
    }
  ]
}
----

[source,yaml]
.jakarta.mail.yaml
----
subjects:
  - command: module name
    jar:
      file: jakarta.mail-2.0.1.jar
      size: 689294
      sha256: 8988bdbde922ee173db7179e23393dd2258f3b64f708f41082e03f0e0494cc23
    result:
      name: jakarta.mail
      source: explicit
      automatic: false
      valid: true
----

== Install

=== Early Access

*JBang*

[source]
[subs="attributes"]
----
// Download, cache, and run
jbang {project-name}-snapshot@{project-owner} &lt;command&gt; [&lt;args&gt;]
----

*manually*

Download the pre-compiled binary matching your OS and processor from the link:https://github.com/{project-owner}/{project-name}/releases/tag/early-access[releases page],
uncompress and copy to the desired location.

NOTE: Be mindful that `{project-name}-early-access.zip` requires Java 11 to be installed while
`{project-name}-standalone-early-access-*.zip` can be used without a previous installation of Java as
it includes its own Java Runtime.

=== Stable

*Sdkman*

Requires Java 11
[source]
[subs="attributes"]
----
sdk install {project-name}
----

*Homebrew tap*

[source]
[subs="attributes"]
----
brew install {project-owner}/tap/{project-name}
----

*Scoop*:

Requires Java 11
[source]
[subs="attributes"]
----
scoop bucket add {project-name} https://github.com/{project-owner}/scoop-{project-name}.git
scoop install {project-name}
----

*JBang*

[source]
[subs="attributes"]
----
// Download, cache, and run
jbang {project-name}@{project-owner} &lt;command&gt; [&lt;args&gt;]
----

*manually*

Download the pre-compiled binary matching your OS and processor from the link:https://github.com/{project-owner}/{project-name}/releases/tag/v{project-version}[releases page],
uncompress and copy to the desired location.

NOTE: Be mindful that `{project-name}-{project-version}.zip` requires Java 11 to be installed while
`{project-name}-standalone-{project-version}-*.zip` can be used without a previous installation of Java as
it includes its own Java Runtime.

== Community

 * Ask questions on our link:https://github.com/{project-owner}/{project-name}/discussions[Discussions] page.
 * image:https://img.shields.io/twitter/follow/{project-owner}?style=social[Twitter Follow]
 * Join our link:CONTRIBUTORS.md[contributors] by reporting bugs, proposing features, sending patches, promoting the project, helping others.

== Code of Conduct

This project adheres to a link:https://github.com/{project-owner}/{project-name}/blob/main/CODE_OF_CONDUCT.md[code of conduct].
By participating, you are expected to uphold this code. We appreciate your contribution. Please refer to our
link:https://github.com/{project-owner}/{project-name}/blob/main/CONTRIBUTING.adoc[contributing guidelines] for further information.
