= JAR file analyzer
:linkattrs:
:project-owner:      kordamp
:project-name:       jarviz
:project-groupId:    org.kordamp.jarviz
:project-artifactId: jarviz-core
:project-version: 0.0.0-SNAPSHOT

image:https://img.shields.io/github/workflow/status/{project-owner}/{project-name}/EarlyAccess?logo=github["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-groupId}/{project-artifactId}.svg[Download, link="https://search.maven.org/#search|ga|1|g:{project-groupId} AND a:{project-artifactId}"]
image:https://slsa.dev/images/gh-badge-level3.svg["SLSA 3", link="https://slsa.dev"]
image:https://img.shields.io/github/downloads/{project-owner}/{project-name}/total[GitHub all releases]

---

Jarviz is a JAR file analyzer tool.  You can obtain metadata from a JAR such as its manifest, manifest entries,
bytecode versions, declarative services, and more.

[source]
----
Jarviz is a JAR file analyzer tool
Usage: jarviz [-hV] [-D=<key=value>]... [COMMAND]

Options:
  -D=<key=value>
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.

Commands:
  bytecode             Commands for the JAR's bytecode
  manifest             Commands for the JAR's manifest
  services             Commands for declarative services
  generate-completion  Generate bash/zsh completion script for jarviz.

Documentation found at https://github.com/kordamp/jarviz
----

== Install

=== Early Access

*JBang*

[source]
[subs="attributes"]
----
// Download, cache, and run
jbang {project-name}-snapshot@{project-owner} &lt;command&gt; [&lt;args&gt;]
----

*manually*

Download the pre-compiled binary matching your OS and processor from the link:https://github.com/{project-owner}/{project-name}/releases/tag/early-access[releases page],
uncompress and copy to the desired location.

NOTE: Be mindful that `{project-name}-early-access.zip` requires Java 11 to be installed while
`{project-name}-standalone-early-access-*.zip` can be used without a previous installation of Java as
it includes its own Java Runtime.

=== Stable

*Sdkman*

Requires Java 11
[source]
[subs="attributes"]
----
sdk install {project-name}
----

*Homebrew tap*

[source]
[subs="attributes"]
----
brew install {project-owner}/tap/{project-name}
----

*Scoop*:

Requires Java 11
[source]
[subs="attributes"]
----
scoop bucket add {project-name} https://github.com/{project-owner}/scoop-{project-name}.git
scoop install {project-name}
----

*JBang*

[source]
[subs="attributes"]
----
// Download, cache, and run
jbang {project-name}@{project-owner} &lt;command&gt; [&lt;args&gt;]
----

*manually*

Download the pre-compiled binary matching your OS and processor from the link:https://github.com/{project-owner}/{project-name}/releases/tag/v{project-version}[releases page],
uncompress and copy to the desired location.

NOTE: Be mindful that `{project-name}-{project-version}.zip` requires Java 11 to be installed while
`{project-name}-standalone-{project-version}-*.zip` can be used without a previous installation of Java as
it includes its own Java Runtime.

== Community

 * Ask questions on our link:https://github.com/{project-owner}/{project-name}/discussions[Discussions] page.
 * image:https://img.shields.io/twitter/follow/{project-owner}?style=social[Twitter Follow]
 * Join our link:CONTRIBUTORS.md[contributors] by reporting bugs, proposing features, sending patches, promoting the project, helping others.

== Code of Conduct

This project adheres to a link:https://github.com/{project-owner}/{project-name}/blob/main/CODE_OF_CONDUCT.md[code of conduct].
By participating, you are expected to uphold this code. We appreciate your contribution. Please refer to our
link:https://github.com/{project-owner}/{project-name}/blob/main/CONTRIBUTING.adoc[contributing guidelines] for further information.
